# Note that Viper is not thread-safe, use as read-only for now
# Placeholder

app: 
  - log_level: debug
coinbase:
  data:
    - price_depth: 3
  channels:
    - name: level2
      product_ids: [ ETH-BTC, ETH-USD ]

