# Note that Viper is not thread-safe, use as read-only for now
# Placeholder

coinbase:
  channels:
    - name: level2
      product_ids: [ ETH-BTC, ETH-USD ]
    - name: heartbeat
      product_ids: [ ETH-BTC, ETH-USD ]

